org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=false
org.gradle.caching=true
org.gradle.parallel=false
net.minecraftforge.gradle.merge-source-sets=false

minecraft_version=1.12.2
minecraft_version_range=[1.12.2]
forge_version=14.23.5.2859
forge_version_range=[14.23.5.2859,)
loader_version_range=[14,)
mapping_channel=stable
mapping_version=39-1.12

loader_name=forge
loader_code=1
java_version=8
java_toolchain_version=8.0.502+7
java_setup_version=8.0.502+7
gradle_java_version=17
curseforge_project_id=240984

mod_id=steamadvantage
mod_name=Steam Advantage
mod_license=GPL-3.0-only
mod_version=2.2.1.112021
mod_group=com.mcmoddev.steamadvantage
mod_authors=DrCyano
mod_description=Steam-powered machines and infrastructure for the Power Advantage platform.

cf_requirements=power-advantage,base-metals
cf_optionals=
cf_versions=1.12.2

poweradvantage_version=2.4.1.112021
poweradvantage_source_repository=MinecraftModDevelopmentMods/PowerAdvantage
poweradvantage_source_ref=40811a0be37174a0633998eb3d820d95755d35e8
poweradvantage_deobf_sha256=DE7759033A094718E1341CC82B9912425A24A035DBD7F91D590D8B921F08DEB2
